In [2]:
import numpy as  np

### ndarray.size

In [200]:
a = np.arange(12).reshape(3, 4)

a.shape
a.size

(3, 4)

12

### `np.fromfunction()` 

In [171]:
def f(i, j):
    return i*100 + j

np.fromfunction(f, (3, 4), dtype=int)

array([[  0,   1,   2,   3],
       [100, 101, 102, 103],
       [200, 201, 202, 203]])

###  One-dimensional `ndarray[start:end:step]` 

In [108]:
type(np.arange(10))

numpy.ndarray

In [102]:
np.arange(100)[0:50:3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [103]:
np.arange(100)[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [104]:
np.arange(100)[::-3]

array([99, 96, 93, 90, 87, 84, 81, 78, 75, 72, 69, 66, 63, 60, 57, 54, 51,
       48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3,  0])

In [105]:
np.arange(100)[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [107]:
print range(100)[::-1]

[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


### Multidimensional ndarray indexing using "`...`"

In [12]:
def f(i, j, k, m):
    return (i+1)*1000 + (j+1)*100 + (k+1)*10 + (m+1)

b = np.fromfunction(f, (3, 4, 5, 6), dtype=int)
b.shape
b

(3, 4, 5, 6)

array([[[[1111, 1112, 1113, 1114, 1115, 1116],
         [1121, 1122, 1123, 1124, 1125, 1126],
         [1131, 1132, 1133, 1134, 1135, 1136],
         [1141, 1142, 1143, 1144, 1145, 1146],
         [1151, 1152, 1153, 1154, 1155, 1156]],

        [[1211, 1212, 1213, 1214, 1215, 1216],
         [1221, 1222, 1223, 1224, 1225, 1226],
         [1231, 1232, 1233, 1234, 1235, 1236],
         [1241, 1242, 1243, 1244, 1245, 1246],
         [1251, 1252, 1253, 1254, 1255, 1256]],

        [[1311, 1312, 1313, 1314, 1315, 1316],
         [1321, 1322, 1323, 1324, 1325, 1326],
         [1331, 1332, 1333, 1334, 1335, 1336],
         [1341, 1342, 1343, 1344, 1345, 1346],
         [1351, 1352, 1353, 1354, 1355, 1356]],

        [[1411, 1412, 1413, 1414, 1415, 1416],
         [1421, 1422, 1423, 1424, 1425, 1426],
         [1431, 1432, 1433, 1434, 1435, 1436],
         [1441, 1442, 1443, 1444, 1445, 1446],
         [1451, 1452, 1453, 1454, 1455, 1456]]],


       [[[2111, 2112, 2113, 2114, 2115, 2116],
   

In [158]:
b[2]

array([[[3111, 3112, 3113, 3114, 3115, 3116],
        [3121, 3122, 3123, 3124, 3125, 3126],
        [3131, 3132, 3133, 3134, 3135, 3136],
        [3141, 3142, 3143, 3144, 3145, 3146],
        [3151, 3152, 3153, 3154, 3155, 3156]],

       [[3211, 3212, 3213, 3214, 3215, 3216],
        [3221, 3222, 3223, 3224, 3225, 3226],
        [3231, 3232, 3233, 3234, 3235, 3236],
        [3241, 3242, 3243, 3244, 3245, 3246],
        [3251, 3252, 3253, 3254, 3255, 3256]],

       [[3311, 3312, 3313, 3314, 3315, 3316],
        [3321, 3322, 3323, 3324, 3325, 3326],
        [3331, 3332, 3333, 3334, 3335, 3336],
        [3341, 3342, 3343, 3344, 3345, 3346],
        [3351, 3352, 3353, 3354, 3355, 3356]],

       [[3411, 3412, 3413, 3414, 3415, 3416],
        [3421, 3422, 3423, 3424, 3425, 3426],
        [3431, 3432, 3433, 3434, 3435, 3436],
        [3441, 3442, 3443, 3444, 3445, 3446],
        [3451, 3452, 3453, 3454, 3455, 3456]]])

In [177]:
b[2, :, :, 3]

array([[3114, 3124, 3134, 3144, 3154],
       [3214, 3224, 3234, 3244, 3254],
       [3314, 3324, 3334, 3344, 3354],
       [3414, 3424, 3434, 3444, 3454]])

In [178]:
b[2,..., 3]

array([[3114, 3124, 3134, 3144, 3154],
       [3214, 3224, 3234, 3244, 3254],
       [3314, 3324, 3334, 3344, 3354],
       [3414, 3424, 3434, 3444, 3454]])

### flatten

In [201]:
b = np.arange(12).reshape(3, 4)

In [202]:
b.reshape(b.size)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [203]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [206]:
bf = b.flat
b.flat
for i in bf:
    print i

0
1
2
3
4
5
6
7
8
9
10
11


### resize()

In [213]:
a = np.arange(12).reshape(3, 4)
a
a.resize(4, 3)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### reshape(i,-1)

In [8]:
a = np.arange(12).reshape(3, 4)
a
a.reshape(4, -1)
a.reshape(-1,)
a.squeeze()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### newaxis

In [3]:
import numpy as np
from numpy import newaxis

In [5]:
a = np.array([1, 2])
a

array([1, 2])

In [6]:
a.reshape(2, 1)

array([[1],
       [2]])

In [7]:
a[:, newaxis]

array([[1],
       [2]])

In [9]:
a[newaxis, :]
a[newaxis, :].shape

array([[1, 2]])

(1, 2)

In [10]:
a[:, newaxis, newaxis]
a[:, newaxis, newaxis].shape

array([[[1]],

       [[2]]])

(2, 1, 1)

### Stacking

In [243]:
np.vstack((np.array([1,2]), np.array([3, 4])))

array([[1, 2],
       [3, 4]])

In [244]:
np.hstack((np.array([1,2]), np.array([3, 4])))

array([1, 2, 3, 4])

In [246]:
np.vstack((np.array([1,2]).reshape(2,1), np.array([3, 4]).reshape(2,1)))

array([[1],
       [2],
       [3],
       [4]])

In [247]:
np.hstack((np.array([1,2]).reshape(2,1), np.array([3, 4]).reshape(2,1)))

array([[1, 3],
       [2, 4]])

In [248]:
np.column_stack((np.array([1,2]), np.array([3, 4])))

array([[1, 3],
       [2, 4]])

### `c_[]`

In [18]:
a1 = np.arange(10)
a2 = np.arange(10, 20)

b = np.concatenate([a1.reshape(-1,1), a2.reshape(-1,1)], axis=1)
b

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [17]:
b = np.c_[a1, a2]
b

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

### Assign, view, and copy

In [249]:
a = np.arange(12)

In [250]:
b = a
c = a.view()
d = a.copy()

In [252]:
b is a
c is a
c.base is a

True

False

True

In [253]:
b.shape = 3, 4

In [254]:
a.shape

(3, 4)

#### View: share data but different shape

In [257]:
c.resize(2, 6)
c[0,4]=1234

In [258]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [259]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

### Indexing by array 

In [267]:
a = np.arange(12)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [270]:
b = np.array([[1, 3, 7, 5]])
a[b]

array([[ 2,  6, 14, 10]])

In [271]:
b = np.array([[1, 3], [7, 5]])
a[b]

array([[ 2,  6],
       [14, 10]])

#### `mgrid`

In [274]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [275]:
np.mgrid[0:5:1,0:5:1]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [278]:
np.mgrid[0:5:3j,0:5:10j]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 2.5       ,  2.5       ,  2.5       ,  2.5       ,  2.5       ,
          2.5       ,  2.5       ,  2.5       ,  2.5       ,  2.5       ],
        [ 5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
          5.        ,  5.        ,  5.        ,  5.        ,  5.        ]],

       [[ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
          2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ],
        [ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
          2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ],
        [ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
          2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ]]])

In [279]:
np.ogrid[0:5, 0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

In [280]:
np.ogrid[0:5:3j,0:5:10j]

[array([[ 0. ],
        [ 2.5],
        [ 5. ]]),
 array([[ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
          2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ]])]

### `vectorize()`

In [282]:
def foo(x, y):
    return max(x-y, y-x)

In [284]:
vec_foo = np.vectorize(foo)

In [287]:
vec_foo([1, 3, 5], [2, 1, 5])

array([1, 2, 0])

### `cast['type']()`

In [292]:
type(np.pi)

float

In [288]:
np.cast['i'](np.pi)

array(3, dtype=int32)

In [295]:
np.cast['f'](np.pi)

array(3.1415927410125732, dtype=float32)

### `select()`

In [299]:
x = np.arange(10)

In [300]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [308]:
np.select([x<3, x>5], [x, x**2], default=12345)

array([    0,     1,     2, 12345, 12345, 12345,    36,    49,    64,    81])

### Use `np.source()` to see sourcecode

In [310]:
np.source(np.select)

In file: /Users/yangzhang/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py

def select(condlist, choicelist, default=0):
    """
    Return an array drawn from elements in choicelist, depending on conditions.

    Parameters
    ----------
    condlist : list of bool ndarrays
        The list of conditions which determine from which array in `choicelist`
        the output elements are taken. When multiple conditions are satisfied,
        the first one encountered in `condlist` is used.
    choicelist : list of ndarrays
        The list of arrays from which the output elements are taken. It has
        to be of the same length as `condlist`.
    default : scalar, optional
        The element inserted in `output` when all conditions evaluate to False.

    Returns
    -------
    output : ndarray
        The output at position m is the m-th element of the array in
        `choicelist` where the m-th element of the corresponding array in
        `condlist` is True.

    S

### References
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- https://docs.scipy.org/doc/scipy/reference/tutorial/basic.html