In [50]:
import numpy as np

In [51]:
x = 1

In [55]:
y = np.array(x)
print(y)
print(y.shape)

1
()


In [56]:
y = np.array(x)[np.newaxis]
print(y)
print(y.shape)

[1]
(1,)


In [58]:
y = np.array(x)[np.newaxis, np.newaxis]
print(y)
print(y.shape)

[[1]]
(1, 1)


In [59]:
y = np.array(x)[np.newaxis, np.newaxis, np.newaxis]
print(y)
print(y.shape)

[[[1]]]
(1, 1, 1)


In [61]:
x = [1, 2, 3]

In [62]:
y = np.array(x)
print(y)
print(y.shape)

[1 2 3]
(3,)


In [63]:
y = np.array(x)[np.newaxis]
print(y)
print(y.shape)

[[1 2 3]]
(1, 3)


In [71]:
y = np.array(x)[np.newaxis, np.newaxis]
print(y)
print(y.shape)

[[[[1 2 3]
   [4 5 6]]]]
(1, 1, 2, 3)


In [74]:
y = np.array(x)[np.newaxis, :, np.newaxis]
print(y)
print(y.shape)

[[[[1 2 3]]

  [[4 5 6]]]]
(1, 2, 1, 3)


In [65]:
y = np.array(x)[:, np.newaxis]
print(y)
print(y.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [67]:
x = [[1, 2, 3], [4, 5, 6]]

In [68]:
y = np.array(x)
print(y)
print(y.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [69]:
y = np.array(x)[np.newaxis]
print(y)
print(y.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
