In [95]:
import numpy as np

In [96]:
def show_array(y):
    print('array:', y)
    print('array.ndim:', y.ndim)
    print('array.shape:', y.shape)

### 0-D

In [97]:
x = np.array(5)
show_array(x)

array: 5
array.ndim: 0
array.shape: ()


#### 0-D to 1-D

In [98]:
y = np.array(x)[np.newaxis]
show_array(y)

array: [5]
array.ndim: 1
array.shape: (1,)


In [99]:
y = np.expand_dims(x, axis=0)
show_array(y)

array: [5]
array.ndim: 1
array.shape: (1,)


Any number >= 0 does the same.

In [100]:
y = np.expand_dims(x, axis=123456)
show_array(y)

array: [5]
array.ndim: 1
array.shape: (1,)


In [101]:
y = x.reshape(-1,)
show_array(y)

array: [5]
array.ndim: 1
array.shape: (1,)


#### 0-D to 2-D

In [102]:
y = np.array(x)[np.newaxis, np.newaxis]
show_array(y)

array: [[5]]
array.ndim: 2
array.shape: (1, 1)


In [103]:
y = np.expand_dims(x, axis=0)
y = np.expand_dims(y, axis=0)
show_array(y)

array: [[5]]
array.ndim: 2
array.shape: (1, 1)


In [104]:
y = x.reshape(-1, 1)
show_array(y)

array: [[5]]
array.ndim: 2
array.shape: (1, 1)


### 1-D

In [105]:
x = np.array([5, 6, 7])
show_array(x)

array: [5 6 7]
array.ndim: 1
array.shape: (3,)


#### 1-D to 2-D

##### Vector to row matrix

In [106]:
y = np.array(x)[np.newaxis, :]
show_array(y)

array: [[5 6 7]]
array.ndim: 2
array.shape: (1, 3)


In [107]:
y = np.array(x)[np.newaxis] # This is short hand of y = np.array(x)[np.newaxis, :]
show_array(y)

array: [[5 6 7]]
array.ndim: 2
array.shape: (1, 3)


In [108]:
y = np.expand_dims(x, axis=0)
show_array(y)

array: [[5 6 7]]
array.ndim: 2
array.shape: (1, 3)


In [109]:
y = x.reshape(1, -1)
show_array(y)

array: [[5 6 7]]
array.ndim: 2
array.shape: (1, 3)


##### Vector to column matrix

In [110]:
y = np.array(x)[:, np.newaxis]
show_array(y)

array: [[5]
 [6]
 [7]]
array.ndim: 2
array.shape: (3, 1)


In [111]:
y = np.expand_dims(x, axis=1)
show_array(y)

array: [[5]
 [6]
 [7]]
array.ndim: 2
array.shape: (3, 1)


Any number >= 1 does the same.

In [112]:
y = np.expand_dims(x, axis=123456)
show_array(y)

array: [[5]
 [6]
 [7]]
array.ndim: 2
array.shape: (3, 1)


In [113]:
y = x.reshape(-1, 1)
show_array(y)

array: [[5]
 [6]
 [7]]
array.ndim: 2
array.shape: (3, 1)


### 2-D

In [114]:
x = np.array([[1, 2, 3], [4, 5, 6]])
show_array(x)

array: [[1 2 3]
 [4 5 6]]
array.ndim: 2
array.shape: (2, 3)


#### 2-D to 3-D

##### Case 1

In [115]:
y = np.array(x)[np.newaxis, :, :]
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


In [116]:
y = np.array(x)[np.newaxis, :]
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


In [117]:
y = np.array(x)[np.newaxis]
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


In [118]:
y = np.expand_dims(x, axis=0)
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


In [119]:
y = x.reshape(-1, 2, 3)
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


In [126]:
y = x.reshape(-1, *x.shape)
show_array(y)

array: [[[1 2 3]
  [4 5 6]]]
array.ndim: 3
array.shape: (1, 2, 3)


##### Case 2

In [121]:
y = np.array(x)[:, np.newaxis, :]
show_array(y)

array: [[[1 2 3]]

 [[4 5 6]]]
array.ndim: 3
array.shape: (2, 1, 3)


In [122]:
y = np.array(x)[:, np.newaxis]
show_array(y)

array: [[[1 2 3]]

 [[4 5 6]]]
array.ndim: 3
array.shape: (2, 1, 3)


In [123]:
y = np.expand_dims(x, axis=1)
show_array(y)

array: [[[1 2 3]]

 [[4 5 6]]]
array.ndim: 3
array.shape: (2, 1, 3)


In [124]:
y = x.reshape(2, 1, 3)
show_array(y)

array: [[[1 2 3]]

 [[4 5 6]]]
array.ndim: 3
array.shape: (2, 1, 3)


In [127]:
y = x.reshape(x.shape[0], -1, x.shape[1])
show_array(y)

array: [[[1 2 3]]

 [[4 5 6]]]
array.ndim: 3
array.shape: (2, 1, 3)


##### Case 3

In [24]:
y = np.array(x)[:, :, np.newaxis]
show_array(y)

array: [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
array.ndim: 3
array.shape: (2, 3, 1)


In [25]:
y = np.expand_dims(x, axis=2)
show_array(y)

array: [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
array.ndim: 3
array.shape: (2, 3, 1)


Any number >= 2 does the same.

In [26]:
y = np.expand_dims(x, axis=123456)
show_array(y)

array: [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
array.ndim: 3
array.shape: (2, 3, 1)


In [128]:
y = x.reshape(*x.shape, -1)
show_array(y)

array: [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
array.ndim: 3
array.shape: (2, 3, 1)
