In [67]:
import numpy as np

import scipy.sparse
import scipy.sparse.linalg

### Sparce matrix

In [91]:
m=10000
n=20000

In [92]:
def generate_matrices(m, n):
    M = np.zeros(m*n)
    M[np.random.choice(n_2, int(0.05*n_2), replace=False)] = np.random.normal()
    M = M.reshape(m, n)
    M_sparse = scipy.sparse.csc_matrix(M)
    return M, M_sparse

In [93]:
A, A_sparse = generate_matrices(m, n)
B, B_sparse = generate_matrices(m, n)

In [94]:
%%time
dist_1 = np.linalg.norm(A - B, ord=2, axis=1)

CPU times: user 1.3 s, sys: 1.88 s, total: 3.18 s
Wall time: 4.25 s


In [95]:
%%time
dist_2 = scipy.sparse.linalg.norm(A_sparse - B_sparse, ord=2, axis=1) 

CPU times: user 1.73 ms, sys: 1.76 ms, total: 3.48 ms
Wall time: 2.36 ms


In [96]:
np.allclose(dist_1, dist_2)

True

### `optimize`

In [ ]:
import scipy.optimize

In [21]:
def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

In [24]:
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = scipy.optimize.minimize(rosen, x0, method='nelder-mead',
               options={'xtol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571


array([ 1.,  1.,  1.,  1.,  1.])

### `linalg`
unless you don’t want to add scipy as a dependency to your numpy program, use scipy.linalg instead of numpy.linalg

https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

In [27]:
import scipy.stats
np.source(scipy.stats.entropy)

In file: /Users/yangzhang/anaconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py

def entropy(pk, qk=None, base=None):
    """Calculate the entropy of a distribution for given probability values.

    If only probabilities `pk` are given, the entropy is calculated as
    ``S = -sum(pk * log(pk), axis=0)``.

    If `qk` is not None, then compute the Kullback-Leibler divergence
    ``S = sum(pk * log(pk / qk), axis=0)``.

    This routine will normalize `pk` and `qk` if they don't sum to 1.

    Parameters
    ----------
    pk : sequence
        Defines the (discrete) distribution. ``pk[i]`` is the (possibly
        unnormalized) probability of event ``i``.
    qk : sequence, optional
        Sequence against which the relative entropy is computed. Should be in
        the same format as `pk`.
    base : float, optional
        The logarithmic base to use, defaults to ``e`` (natural logarithm).

    Returns
    -------
    S : float
        The calculated entropy.

  

### stats
https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html

In [28]:
from scipy import stats

In [31]:
stats.norm.a, stats.norm.b

(-inf, inf)

In [44]:
rv = stats.norm()

In [45]:
isinstance(stats.norm, stats.rv_continuous)
isinstance(stats.binom, stats.rv_discrete)

True

True

In [46]:
type(stats.norm)

scipy.stats._continuous_distns.norm_gen

In [47]:
type(rv)

scipy.stats._distn_infrastructure.rv_frozen

In [56]:
rv.rvs(size=5)

array([ 1.87897122,  0.63837885,  1.11533126,  0.6056136 , -0.02564832])

In [59]:
# set seeds
rv.rvs(size=5, random_state=1234)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873])

### References
- https://docs.scipy.org/doc/scipy/reference/tutorial/index.html